# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f019180857115c658affab80c9f1f036"
name = "abra-demo"
handle = "abra-demo"
application_url = "https://timothy-triple-council-rocket.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [
  "https://timothy-triple-council-rocket.trycloudflare.com/auth/callback",
  "https://timothy-triple-council-rocket.trycloudflare.com/auth/shopify/callback",
  "https://timothy-triple-council-rocket.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false

[build]
dev_store_url = "quickstart-e8a80b5c.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
